vlad_change_get_placemark_info:
   path:     /getPlacemarkInfo/{id}
   defaults: { _controller: VladChangeMainBundle:Api:getPlacemarkInfo }
   requirements:
      id: \d+

vlad_change_getPlacemark:
   path:     /getAllPlacemark
   defaults: { _controller: VladChangeMainBundle:Api:getAllPlacemark }

   # vlad_change_addPlacemark:
#     path:     /api.addPlacemark/{x}&{y}
#     defaults: { _controller: VladChangeMainBundle:Api:addPlacemark }

# vlad_change_get_placemark_info:
#     path:     /api/getplacemarkInfo/
#     defaults: { _controller: VladChangeMainBundle:Api:getAllPlacemark }

# vlad_change_getPlacemark:
#     path:     /api.getAllPlacemark
#     defaults: { _controller: VladChangeMainBundle:Api:getAllPlacemark }