vlad_change_main_homepage:
   path: /
   defaults: { _controller: VladChangeMainBundle:Default:index }

vlad_change_view_profile:
    path:     /profile/{id}
    defaults: { _controller: FOSUserBundle:Profile:show }
    requirements:
        id: \d+

vlad_change_edit_project:
    path: /edit_project/{id}
    defaults: { _controller: VladChangeMainBundle:Default:editProject }
    requirements:
        id: \d+

vlad_change_add_project:
    path: /add_project/
    defaults: { _controller: VladChangeMainBundle:Default:addProject }

vlad_change_manipulate_project:
    path: /project/{type}
    defaults: { _controller: VladChangeMainBundle:Default:manipulateProject }
    requirements:
        type:  archive|delete

vlad_change_add_project_from_map:
    path: /add_project/?lat={x}&lon={y}
    defaults: { _controller: VladChangeMainBundle:Default:addProject }

vlad_change_addPlacemark:
    path:     /api.addPlacemark/{x}&{y}
    defaults: { _controller: VladChangeMainBundle:Api:addPlacemark }

vlad_change_getPlacemark:
    path:     /api.getAllPlacemark
    defaults: { _controller: VladChangeMainBundle:Api:getAllPlacemark }
