vlad_change_main_homepage:
   path: /
   defaults: { _controller: VladChangeMainBundle:Default:index }

vlad_change_profile_get_placemarks:
    path:     /profile/api/getAllPlacemark
    defaults: { _controller: VladChangeMainBundle:Api:getAllPlacemark }

vlad_change_view_profile:
    path:     /profile/{id}
    defaults: { _controller: FOSUserBundle:Profile:show }
    requirements:
        id: \d+

vlad_change_edit_avatar:
    path:     /profile/edit/avatar
    defaults: { _controller: VladChangeUserBundle:Profile:editAvatar }

vlad_change_edit_project:
    path: /edit_project/{id}
    defaults: { _controller: VladChangeMainBundle:Default:editProject }
    requirements:
        id: \d+

vlad_change_add_project:
    path: /add_project/
    defaults: { _controller: VladChangeMainBundle:Default:addProject }

vlad_change_manipulate_project:
    path: /project/{type}
    defaults: { _controller: VladChangeMainBundle:Default:manipulateProject }
    requirements:
        type:  archive|delete

vlad_change_add_project_from_map:
    path: /add_project/?lat={x}&lon={y}
    defaults: { _controller: VladChangeMainBundle:Default:addProject }

vlad_change_main_list:
    path: /list
    defaults: { _controller: VladChangeMainBundle:Default:list }

vlad_change_upload_image:
    path:     /upload
    defaults: { _controller: VladChangeMainBundle:Default:uploadImage }

vlad_change_resize_image:
    path:     /resizeimage
    defaults: { _controller: VladChangeMainBundle:Default:resizeImage }

vlad_change_get_image:
    path:     /img/{id}_{param}
    defaults: { _controller: VladChangeMainBundle:Default:getImage }

vlad_change_get_root_image:
    path:     /img/{id}
    defaults: { _controller: VladChangeMainBundle:Default:getRootImage }

vlad_change_delete_image:
    path:     /delete_image
    defaults: { _controller: VladChangeMainBundle:Default:deleteImage }
