vlad_change_main_homepage:
   path: /
   defaults: { _controller: VladChangeMainBundle:Default:index }

vlad_change_view_profile:
    path:     /profile/{id}
    defaults: { _controller: VladChangeMainBundle:Default:viewProfile }
