# vlad_change_store:
#     resource: "@VladChangeStoreBundle/Controller/"
#     type:     annotation
#     prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

vlad_change_main:
    resource: "@VladChangeMainBundle/Resources/config/api_routing.yml"
    prefix:   /api


vlad_change_main:
    resource: "@VladChangeMainBundle/Resources/config/routing.yml"
    prefix:   /
